services:
  app:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=${POSTGRES_CONNECTION}
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true